### ISSUE TITLE
Sector color all the same color "blue" ; should be different colors like Android app

### ISSUE THREAD

**Issue by mystica555** [CellMapper/Map-BETA#6] opened 2017-07-21 01:25 UTC
# Basic Info
Chrome 58/linux

# Steps to reproduce
Click on tower to view coverage pattern blobs
# Current behavior
All blue
# Expected behavior
Multicolor so that each blob can be easier distinguished
Mirror the exact strategy used in the Android app. Please....

# Video/Screenshot link (optional)

**Comment by jessenic** [comment] 2017-07-21 10:51
Duplicate of #2, will be implemented.

**Closed** 2017-07-21 10:55 UTC
Labels: suggestion
